### ISSUE TITLE
What is HYDRO_HWTYPE for?

### ISSUE THREAD

**Issue by spinda** [jedisct1/libhydrogen#50]
It's set by `Makefile.arduino`, and default-initialized in `hydrogen.h`, but I can't find any place it's actually used.

**Comment by jedisct1** [comment]
The `AVR` macro being defined is not enough to know about what exact microcontroller is being used, what timers are available, or more generally what we can use for entropy extraction.

The AVR code path currently only supports the ATMEGA328 since I use an Arduino Uno, but the idea of this macro was to support other boards/microcontrollers.

**Comment by spinda** [comment]
Got it. Thanks!
